use std::collections::BTreeMap;
use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

/// Maps each logo file stem to its path, in the byte-sorted order `logo.rs` searches.
fn collect(assets: &Path, set: &str) -> BTreeMap<String, PathBuf> {
    let mut map = BTreeMap::new();
    let dir = assets.join(set);
    if !dir.is_dir() {
        return map;
    }
    for letter_dir in fs::read_dir(&dir).unwrap().filter_map(|e| e.ok()) {
        let p = letter_dir.path();
        if !p.is_dir() {
            continue;
        }
        for file in fs::read_dir(&p).unwrap().filter_map(|e| e.ok()) {
            let f = file.path();
            if f.extension().and_then(|e| e.to_str()) != Some("txt") {
                continue;
            }
            let Some(stem) = f.file_stem().and_then(|e| e.to_str()) else {
                continue;
            };
            map.insert(stem.to_string(), f);
        }
    }
    map
}

/// Writes the sorted logo tables into the generated source, with paths left relative to CARGO_MANIFEST_DIR.
fn emit(out: &mut String, name: &str, assets: &Path, set: &str, map: &BTreeMap<String, PathBuf>) {
    let _ = writeln!(
        out,
        "pub static {}: &[(&str, &str)] = &[",
        name.to_uppercase()
    );
    for (key, path) in map {
        let Ok(rel) = path.strip_prefix(assets) else {
            continue;
        };
        let rel = rel.to_string_lossy().replace('\\', "/");
        let _ = writeln!(
            out,
            "    ({:?}, include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/assets/{}\"))),",
            key, rel
        );
    }
    out.push_str("];\n\n");
    let _ = set;
}

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let assets = manifest.join("assets");
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest = Path::new(&out_dir).join("logos.rs");

    let mut code = String::from("// @generated by build.rs\n\n");
    emit(
        &mut code,
        "normal",
        &assets,
        "normal",
        &collect(&assets, "normal"),
    );
    emit(
        &mut code,
        "mini",
        &assets,
        "mini",
        &collect(&assets, "mini"),
    );
    // Key order comes from the BTreeMap, letting the generated lookup binary search the table.
    code.push_str(
        "#[inline]\n\
         fn table(set: &str) -> &'static [(&'static str, &'static str)] {\n    \
             match set { \"mini\" => MINI, _ => NORMAL }\n\
         }\n\n\
         #[inline]\n\
         pub fn get(set: &str, key: &str) -> Option<&'static str> {\n    \
             let table = table(set);\n    \
             table.binary_search_by_key(&key, |(k, _)| *k).ok().map(|i| table[i].1)\n\
         }\n\n\
         #[inline]\n\
         pub fn has(set: &str, key: &str) -> bool {\n    \
             table(set).binary_search_by_key(&key, |(k, _)| *k).is_ok()\n\
         }\n",
    );

    fs::write(&dest, code).unwrap();
    println!("cargo:rerun-if-changed=assets");
}
